@Library('jenkins-shared-library@main') _

pipeline {

    agent any

    parameters {

        choice(
            name: 'action',
            choices: 'create\nrollback',
            description: 'Create or rollback the deployment'
        )

        string(
            name: 'ImageName',
            defaultValue: 'kubernetes-configmap-reload',
            description: 'Name of the Docker image'
        )

        string(
            name: 'ImageTag',
            defaultValue: 'v1',
            description: 'Docker image tag'
        )

        string(
            name: 'AppName',
            defaultValue: 'kubernetes-configmap-reload',
            description: 'Name of the Application'
        )

        string(
            name: 'docker_repo',
            defaultValue: 'gopinadh66',
            description: 'Docker Hub username'
        )
    }


    tools {
        maven 'maven3'
    }


    stages {

        stage('Git-Checkout') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                gitCheckout(
                    branch: 'main',
                    url: 'https://github.com/GopiNadh22/jenkins-ci-cd-pipeline-aws-docker.git'
                )
            }
        }


        stage('Build-Maven') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                dir("${params.AppName}") {

                    sh '''
                        echo "======================================"
                        echo "JAVA VERSION"
                        echo "======================================"

                        java -version
                        javac -version

                        echo "======================================"
                        echo "MAVEN VERSION"
                        echo "======================================"

                        mvn --version

                        echo "======================================"
                        echo "MAVEN BUILD"
                        echo "======================================"

                        mvn clean package -Dmaven.test.skip=true
                    '''
                }
            }
        }


        stage('Docker Build and Push') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                dir("${params.AppName}") {

                    dockerBuild(
                        "${params.ImageName}",
                        "${params.docker_repo}",
                        "${params.ImageTag}"
                    )
                }
            }
        }


        stage('Docker Cleanup') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                dockerCleanup(
                    "${params.ImageName}",
                    "${params.docker_repo}",
                    "${params.ImageTag}"
                )
            }
        }


        stage('Ansible Setup') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                sh """
                    echo "======================================"
                    echo "ANSIBLE SETUP"
                    echo "======================================"

                    ansible-playbook \
                    ${WORKSPACE}/kubernetes-configmap-reload/server_setup.yml
                """
            }
        }


        stage('Create Deployment') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                sh """
                    echo "======================================"
                    echo "KUBERNETES DEPLOYMENT"
                    echo "======================================"

                    kubectl apply -f \
                    ${WORKSPACE}/kubernetes-configmap-reload/kubernetes-configmap.yml
                """
            }
        }


        stage('Wait for Pods') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                sh """
                    echo "======================================"
                    echo "WAITING FOR DEPLOYMENT"
                    echo "======================================"

                    kubectl rollout status \
                    deployment/${params.AppName} \
                    --timeout=300s
                """
            }
        }


        stage('Rollback Deployment') {

            when {
                expression {
                    params.action == 'rollback'
                }
            }

            steps {

                sh """
                    echo "======================================"
                    echo "ROLLBACK DEPLOYMENT"
                    echo "======================================"

                    kubectl delete deployment ${params.AppName} \
                    --ignore-not-found=true

                    kubectl delete service ${params.AppName} \
                    --ignore-not-found=true
                """
            }
        }
    }


    post {

        success {

            echo "======================================"
            echo "PIPELINE COMPLETED SUCCESSFULLY"
            echo "======================================"
        }


        failure {

            echo "======================================"
            echo "PIPELINE FAILED"
            echo "CHECK THE FAILED STAGE"
            echo "======================================"
        }
    }
}
