@Library('jenkins-shared-library@main') _

pipeline {

    agent any

    parameters {

        choice(
            name: 'action',
            choices: 'create\nrollback',
            description: 'Create or rollback the deployment'
        )

        string(
            name: 'ImageName',
            description: 'Name of the Docker image',
            defaultValue: 'kubernetes-configmap-reload'
        )

        string(
            name: 'ImageTag',
            description: 'Docker image tag',
            defaultValue: 'v1'
        )

        string(
            name: 'AppName',
            description: 'Name of the Application',
            defaultValue: 'kubernetes-configmap-reload'
        )

        string(
            name: 'docker_repo',
            description: 'Docker Hub username',
            defaultValue: 'gopinadh66'
        )
    }

    tools {
        maven 'maven3'
    }

    stages {

        stage('Git-Checkout') {
            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {
                gitCheckout(
                    branch: 'main',
                    url: 'https://github.com/GopiNadh22/jenkins-ci-cd-pipeline-aws-docker.git'
                )
            }
        }


        stage('Build-Maven') {
            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {
                dir("${params.AppName}") {

                    sh '''
                        echo "===== JAVA VERSION ====="
                        java -version
                        javac -version

                        echo "===== MAVEN VERSION ====="
                        mvn --version

                        echo "===== MAVEN BUILD ====="
                        mvn clean package
                    '''
                }
            }
        }


        stage('DockerBuild and Push') {
            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {
                dir("${params.AppName}") {

                    dockerBuild(
                        "${params.ImageName}",
                        "${params.docker_repo}"
                    )
                }
            }
        }


        stage('Docker-CleanUP') {
            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                dockerCleanup(
                    "${params.ImageName}",
                    "${params.docker_repo}"
                )
            }
        }


        stage('Ansible Setup') {
            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                sh '''
                    ansible-playbook \
                    ${WORKSPACE}/kubernetes-configmap-reload/server_setup.yml
                '''
            }
        }


        stage('Create Deployment') {
            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                sh '''
                    echo "===== DEPLOYING APPLICATION ====="

                    kubectl apply -f \
                    ${WORKSPACE}/kubernetes-configmap-reload/kubernetes-configmap.yml
                '''
            }
        }


        stage('Wait for Pods') {
            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                sh '''
                    echo "===== WAITING FOR DEPLOYMENT ====="

                    kubectl rollout status \
                    deployment/${AppName} \
                    --timeout=300s
                '''
            }
        }


        stage('Rollback Deployment') {
            when {
                expression {
                    params.action == 'rollback'
                }
            }

            steps {

                sh '''
                    echo "===== ROLLING BACK APPLICATION ====="

                    kubectl delete deployment ${AppName} \
                    --ignore-not-found=true

                    kubectl delete service ${AppName} \
                    --ignore-not-found=true
                '''
            }
        }
    }


    post {

        success {
            echo "=========================================="
            echo "PIPELINE COMPLETED SUCCESSFULLY"
            echo "=========================================="
        }

        failure {
            echo "=========================================="
            echo "PIPELINE FAILED"
            echo "Check the failed stage logs"
            echo "=========================================="
        }
    }
}
