@Library('jenkins-shared-library@main') _

pipeline {

    agent any

    parameters {

        choice(
            name: 'action',
            choices: 'create\nrollback',
            description: 'Create or rollback the deployment'
        )

        string(
            name: 'ImageName',
            description: 'Name of the Docker image',
            defaultValue: 'kubernetes-configmap-reload'
        )

        string(
            name: 'ImageTag',
            description: 'Docker image tag',
            defaultValue: 'v1'
        )

        string(
            name: 'AppName',
            description: 'Name of the Application',
            defaultValue: 'kubernetes-configmap-reload'
        )

        string(
            name: 'docker_repo',
            description: 'Docker Hub username',
            defaultValue: 'gopinadh66'
        )
    }


    tools {
        maven 'maven3'
    }


    stages {

        /*
        ======================================
        STAGE 1: GIT CHECKOUT
        ======================================
        */

        stage('Git-Checkout') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                gitCheckout(
                    branch: 'main',
                    url: 'https://github.com/GopiNadh22/jenkins-ci-cd-pipeline-aws-docker.git'
                )
            }
        }


        /*
        ======================================
        STAGE 2: MAVEN BUILD
        ======================================
        */

        stage('Build-Maven') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                dir("${params.AppName}") {

                    sh '''
                        echo "======================================"
                        echo "JAVA VERSION"
                        echo "======================================"

                        java -version
                        javac -version


                        echo "======================================"
                        echo "MAVEN VERSION"
                        echo "======================================"

                        mvn --version


                        echo "======================================"
                        echo "MAVEN BUILD"
                        echo "======================================"

                        mvn clean package -Dmaven.test.skip=true
                    '''
                }
            }
        }


        /*
        ======================================
        STAGE 3: DOCKER BUILD AND PUSH
        ======================================
        */

        stage('DockerBuild and Push') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                dir("${params.AppName}") {

                    dockerBuild(
                        "${params.ImageName}",
                        "${params.docker_repo}",
                        "${params.ImageTag}"
                    )
                }
            }
        }


        /*
        ======================================
        STAGE 4: DOCKER CLEANUP
        ======================================
        */

        stage('Docker-CleanUP') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                dockerCleanup(
                    "${params.ImageName}",
                    "${params.docker_repo}",
                    "${params.ImageTag}"
                )
            }
        }


        /*
        ======================================
        STAGE 5: ANSIBLE SETUP
        ======================================
        */

        stage('Ansible Setup') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                sh '''
                    echo "======================================"
                    echo "ANSIBLE SETUP"
                    echo "======================================"

                    ansible-playbook \
                    ${WORKSPACE}/kubernetes-configmap-reload/server_setup.yml
                '''
            }
        }


        /*
        ======================================
        STAGE 6: KUBERNETES DEPLOYMENT
        ======================================
        */

        stage('Create Deployment') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                sh '''
                    echo "======================================"
                    echo "KUBERNETES DEPLOYMENT"
                    echo "======================================"

                    kubectl apply -f \
                    ${WORKSPACE}/kubernetes-configmap-reload/kubernetes-configmap.yml
                '''
            }
        }


        /*
        ======================================
        STAGE 7: WAIT FOR PODS
        ======================================
        */

        stage('Wait for Pods') {

            when {
                expression {
                    params.action == 'create'
                }
            }

            steps {

                sh '''
                    echo "======================================"
                    echo "WAITING FOR DEPLOYMENT"
                    echo "======================================"

                    kubectl rollout status \
                    deployment/${AppName} \
                    --timeout=300s
                '''
            }
        }


        /*
        ======================================
        STAGE 8: ROLLBACK
        ======================================
        */

        stage('Rollback Deployment') {

            when {
                expression {
                    params.action == 'rollback'
                }
            }

            steps {

                sh '''
                    echo "======================================"
                    echo "ROLLBACK DEPLOYMENT"
                    echo "======================================"

                    kubectl delete deployment ${AppName} \
                    --ignore-not-found=true

                    kubectl delete service ${AppName} \
                    --ignore-not-found=true
                '''
            }
        }
    }


    /*
    ======================================
    PIPELINE RESULT
    ======================================
    */

    post {

        success {

            echo "======================================"
            echo "PIPELINE COMPLETED SUCCESSFULLY"
            echo "======================================"
        }

        failure {

            echo "======================================"
            echo "PIPELINE FAILED"
            echo "CHECK THE FAILED STAGE"
            echo "======================================"
        }
    }
}
